# Number of worker nodes to be created
NUM_WORKER_NODES=2

$default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`

Vagrant.configure("2") do |config|

  # Manage the /etc/hosts files in the VMs
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.box_check_update = true

  # config.vm.network "forwarded_port", guest: 3000, host: 3000
  # config.vm.network "forwarded_port", guest: 3100, host: 3100
  # config.vm.network "forwarded_port", guest: 9090, host: 9090

# Configue the VM for controlplane
  config.vm.define "controlplane" do |controlplane|
    controlplane.vm.box = 'generic/ubuntu2204'
    controlplane.vm.network "private_network", ip: '10.0.0.10'
    controlplane.vm.network "public_network", bridge: "#$default_network_interface"
    # controlplane.ssh.insert_key = false
    controlplane.vm.hostname = "controlplane"
    controlplane.vm.synced_folder "./data", "/vagrant"
    controlplane.vm.provider "virtualbox" do |vb|
      vb.name = "controlplane"
      vb.cpus = '2'
      vb.memory = '1800'
    end
    controlplane.vm.provision "shell", path: "scripts/common.sh"
    controlplane.vm.provision "shell", path: "scripts/controlplane.sh"
  end

# Configure Worker Nodes
  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = 'generic/ubuntu2204'
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.network "public_network", bridge: "#$default_network_interface"
      # node.ssh.insert_key = false
      node.vm.hostname = "node-#{i}"
      node.vm.synced_folder "./data", "/vagrant"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node-#{i}"
        vb.cpus = '1'
        vb.memory = '1000'
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
  end
end
